"""mkexports.py -- a Portable app's EXPORT table (docs/2026-10-01-IMPORT-TABLE.md).

    tools/mkexports.py <first-link.elf> -o exports.s

The app is linked twice: once without the table, to learn its symbols, and
once with the generated table.  The table names its symbols rather than
their addresses (`.quad <symbol>`), so the second link resolves it and the
two links need not agree on any address.

What is exported is the runtime: every global `fpr_` symbol except the
program's own functions and objects (`fpr_fn_`, `fpr_obj_`) and its module
tables.  A plugin carries its own copy of the code it was compiled with (its
prelude, its modules) and imports only the runtime, by name
(tools/mkimports.py); the loader in qos/appside/plugimg.c reads this table.

Layout (qos_abi.h, qos_export_t): a count word, then rows of
{name pointer, address, size}, sorted by name.
"""
import sys, argparse, os

sys.path.insert(0, os.path.dirname(__file__))
from mkqa import elf_symbols, SHN_UNDEF, SHN_ABS

STB_GLOBAL = 1

def exported(name):
    return (name.startswith("fpr_") and not name.startswith(("fpr_fn_", "fpr_obj_"))
            and name not in ("fpr_modtab", "fpr_contab"))

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("elf")
    ap.add_argument("-o", "--out", required=True)
    a = ap.parse_args()
    with open(a.elf, "rb") as f:
        elf = f.read()
    syms = {}
    for n, _v, size, shndx, bind in elf_symbols(elf):
        if bind == STB_GLOBAL and shndx not in (SHN_UNDEF, SHN_ABS) and exported(n):
            syms[n] = size
    names = sorted(syms)
    out = ["# generated by tools/mkexports.py: the runtime this app exports to plugins",
           "    .section .rodata.qos_exports,\"a\",@progbits",
           "    .balign 8", "    .globl qos_exports", "qos_exports:",
           f"    .quad {len(names)}"]
    for i, n in enumerate(names):
        out += [f"    .quad .Lqx{i}", f"    .quad {n}", f"    .quad {syms[n]}"]
    for i, n in enumerate(names):
        out += [f".Lqx{i}:", f"    .asciz \"{n}\""]
    with open(a.out, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"mkexports: {len(names)} runtime symbols")

if __name__ == "__main__":
    main()
