"""mkimports.py -- a Portable plugin's IMPORTS (docs/2026-10-01-IMPORT-TABLE.md).

    tools/mkimports.py --arch a64|x64 <first-link.elf> -o imports.s

A plugin is linked at 0 and placed wherever the running app's buddy puts
it, so it cannot reach the app's symbols by address.  This reads the
symbols a first link (`--unresolved-symbols=ignore-all`) left undefined and
writes, for each, a definition inside the plugin that the loader completes
BY NAME from the app's export table (tools/mkexports.py):

  - a FUNCTION gets a stub that jumps through a slot,
      `__qosimp_c_<name>`, which receives the exporter's address;
  - DATA gets a placeholder of the object's ABI size, `__qosimp_d<n>_<name>`,
    which receives a COPY of the exporter's object.  Only immutable objects
    with a fixed layout may be imported this way: the static Unit/True/False
    headers, a primitive's static closure (`fpr_g_<name>`, a pap0_t), and
    x86-64's TLS displacement (set once at boot, before any plugin loads).
    Any other data import is refused here, by name.

mkqa.py --imports turns the markers into the IMPORT section.
"""
import sys, argparse, re

sys.path.insert(0, __import__("os").path.dirname(__file__))
from mkqa import elf_symbols, SHN_UNDEF

STB_WEAK = 2
HDR = 8          # hdr_t: tid, var
PAP0 = 32        # pap0_t: tid, var, fn, arity, nargs

def data_size(name):
    if name in ("fpr_true", "fpr_false", "fpr_unit"):
        return HDR
    if name == "fpr_g_tlsoff":
        return 8
    if name.startswith("fpr_g_") and not re.search(r"_call[0-9]+$", name):
        return PAP0  # a primitive used as a value: its static closure
    return None

def is_function(name):
    return data_size(name) is None

STUB = {
    "a64": ["    adrp x16, __qosimp_c_{n}",
            "    ldr x16, [x16, :lo12:__qosimp_c_{n}]",
            "    br x16"],
    "x64": ["    jmp *__qosimp_c_{n}(%rip)"],
}

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--arch", choices=("a64", "x64"), required=True)
    ap.add_argument("elf")
    ap.add_argument("-o", "--out", required=True)
    a = ap.parse_args()
    with open(a.elf, "rb") as f:
        elf = f.read()
    names = sorted({n for n, _v, _s, shndx, bind in elf_symbols(elf)
                    if shndx == SHN_UNDEF and n and bind != STB_WEAK})
    out = ["# generated by tools/mkimports.py: the plugin's imports, completed by",
           "# the loader from the app's export table (docs/2026-10-01-IMPORT-TABLE.md)"]
    for n in names:
        if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_.$]*", n):
            raise SystemExit(f"mkimports: cannot stub the symbol {n!r}")
        size = data_size(n)
        if size is None and not n.startswith("fpr_"):
            raise SystemExit(f"mkimports: the plugin needs {n}, which is not part of the "
                             f"runtime an app exports")
        if size is None:
            out += ["    .section .text.qosimp,\"ax\",@progbits", "    .balign 4",
                    f"    .globl {n}", f"{n}:"]
            out += [l.format(n=n) for l in STUB[a.arch]]
            out += ["    .section .data.qosimp,\"aw\",@progbits", "    .balign 8",
                    f"    .globl __qosimp_c_{n}", f"__qosimp_c_{n}:", "    .quad 0"]
        else:
            out += ["    .section .data.qosimp,\"aw\",@progbits", "    .balign 8",
                    f"    .globl {n}", f"    .globl __qosimp_d{size}_{n}",
                    f"{n}:", f"__qosimp_d{size}_{n}:", f"    .zero {size}"]
    with open(a.out, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"mkimports: {len(names)} imports ({sum(1 for n in names if is_function(n))} functions)")

if __name__ == "__main__":
    main()
